### ISSUE TITLE
Dates are in a confusing format

### ISSUE THREAD

**Issue by jpeg729** [MicrosoftDocs/TeamBlogFeedback#100] opened 2018-07-04 20:03 UTC
The publication date is "02/07/2018".
Being British I find this date format to be highly confusing. I naturally read "2nd of July, 2018", but I think you mean "February 7th, 2018" right?

Please consider using a less ambiguous date format, e.g. "2018/02/07" or "February 7th, 2018".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by ghshephard** [comment] 2018-07-05 15:01
Not just for the British - I'm  located in Michigan, but, working on the Web - you have zero context for what the Date Format will be - so "02/07/2018" is essentially 50% chance either direction.  I can see no downside, but many upsides for adopting either of your eminently reasonable suggestions for a less ambiguous date format.

**Comment by AlanMcBee** [comment] 2018-07-10 00:59
It's 2018. Why isn't 100% of the technology community using ISO 8601 formats by now? 2018-02-07. Easy for everyone.

**Comment by ShevaDas** [comment] 2018-07-10 22:11
This is a duplicate of https://github.com/MicrosoftDocs/feedback/issues/386. I'm going to close this out in favor of that issue, as we don't use this repo for site feedback.

**Closed by ShevaDas** 2018-07-10 22:11 UTC
